const img = 'https://img.freepik.com/fotos-gratis/imagem-aproximada-em-tons-de-cinza-de-uma-aguia-careca-americana-em-um-fundo-escuro_181624-31795.jpg?w=200';
arrayCards = [
  {
    cardName: 'IpsumLoren',
    cardDescription: 'IpsumLorenIpsumLoren',
    cardAttr1: 45,
    cardAttr2: 60,
    cardAttr3: 45,
    cardImage: img,
    cardRare: 'normal',
    cardTrunfo: false,
    hasTrunfo: false,
  },
  {
    cardName: 'IpsumLoren',
    cardDescription: 'IpsumLorenIpsumLoren',
    cardAttr1: 45,
    cardAttr2: 60,
    cardAttr3: 45,
    cardImage: img,
    cardTrunfo: false,
    hasTrunfo: false,
  },
  {
    cardName: 'IpsumLoren',
    cardDescription: 'IpsumLorenIpsumLoren',
    cardAttr1: 45,
    cardAttr2: 60,
    cardAttr3: 45,
    cardImage: img,
    cardTrunfo: false,
    hasTrunfo: false,
  },
  {
    cardName: 'IpsumLoren',
    cardDescription: 'IpsumLorenIpsumLoren',
    cardAttr1: 45,
    cardAttr2: 60,
    cardAttr3: 45,
    cardImage: img,
    cardTrunfo: true,
    hasTrunfo: false,
  },
  {
    cardName: 'IpsumLoren',
    cardDescription: 'IpsumLorenIpsumLoren',
    cardAttr1: 45,
    cardAttr2: 60,
    cardAttr3: 45,
    cardImage: img,
    cardRare: 'normal',
    cardTrunfo: false,
    hasTrunfo: false,
  },
];
